project:
  type: book

book:
  title: "Computational Population Genetics and Statistical Inference in R"
  subtitle: "Learning the fundamentals of population genetics through computer simulations"
  author: "Martin Petr"
  date: "last-modified"
  chapters:
    - index.qmd
    - part: r-intro.qmd
      chapters:
      - r-bootcamp.qmd
    - part: "Welcome to _tidyverse_"
      chapters:
      - tidy-basics.qmd
      - tidy-advanced.qmd
      - tidy-viz.qmd
    - part: "Reproducible computing"
      chapters:
      - repro-projects.qmd
      - repro-quarto.qmd
    - part: "Working with spatial data"
      chapters:
      - spatial-sf.qmd
    - part: "Simulations with _slendr_"
      chapters:
      - popgen-models.qmd
      - popgen-stats.qmd
    - part: "Simulation-based inference"
      chapters:
      - inference-afs.qmd
    - part: handouts.qmd
      chapters:
      - handouts_r-bootcamp.qmd
      - handouts_tidy-basics.qmd
      - handouts_tidy-viz.qmd
      - handouts_slendr.qmd
    - references.qmd
    - acknowledgements.qmd
    - part: "Unfinished chapters"
      chapters:
      - popgen-nonspatial-pca.qmd
      - popgen-spatial-pca.qmd
      - popgen-tracts-dating.qmd
      - popgen-selection.qmd
      - r-thinking.qmd
      - repro-cli.qmd
  appendices:
    - setup-tidyverse.qmd
    - setup-slendr.qmd
    - slides.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
